name= input("Name: ")


if len(name)==5:

 print("First letter sequence:")
 if(name[0]=="a"):
    print("1")
 elif(name[0]=="b"):
    print("2")
 elif(name[0]=="c"):
    print("3")
 elif(name[0]=="d"):
     print("4")
 elif(name[0]=="e"):
     print("5")
 elif(name[0]=="f"):
     print("6")
 elif(name[0]=="g"):
     print("7")
 elif(name[0]=="h"):
     print("8")
 elif(name[0]=="i"):
     print("9")
 elif(name[0]=="j"):
     print("10")
 elif(name[0]=="k"):
     print("11")
 elif(name[0]=="l"):
     print("12")
 elif(name[0]=="m"):
     print("13")
 elif(name[0]=="n"):
     print("14")
 elif(name[0]=="o"):
     print("15")
 elif(name[0]=="p"):
     print("16")
 elif(name[0]=="q"):
     print("17")
 elif(name[0]=="r"):
     print("18")
 elif(name[0]=="s"):
     print("19")
 elif(name[0]=="t"):
     print("20")
 elif(name[0]=="u"):
     print("21")
 elif(name[0]=="v"):
     print("22")
 elif(name[0]=="w"):
     print("23")
 elif(name[0]=="x"):
     print("24")
 elif(name[0]=="y"):
     print("25")
 elif(name[0]=="z"):
     print("26")
 else:
     print("not in the paremitter")
 
 print("Second letter sequence:")
 if(name[1]=="a"):
     print("1")
 elif(name[1]=="b"):
     print("2")
 elif(name[1]=="c"):
     print("3")
 elif(name[1]=="d"):
     print("4")
 elif(name[1]=="e"):
     print("5")
 elif(name[1]=="f"):
     print("6")
 elif(name[1]=="g"):
     print("7")
 elif(name[1]=="h"):
     print("8")
 elif(name[1]=="i"):
     print("9")
 elif(name[1]=="j"):
     print("10")
 elif(name[1]=="k"):
     print("11")
 elif(name[1]=="l"):
     print("12")
 elif(name[1]=="m"):
     print("13")
 elif(name[1]=="n"):
     print("14")
 elif(name[1]=="o"):
     print("15")
 elif(name[1]=="p"):
     print("16")
 elif(name[1]=="q"):
     print("17")
 elif(name[1]=="r"):
     print("18")
 elif(name[1]=="s"):
     print("19")
 elif(name[1]=="t"):
     print("20")
 elif(name[1]=="u"):
     print("21")
 elif(name[1]=="v"):
     print("22")
 elif(name[1]=="w"):
     print("23")
 elif(name[1]=="x"):
     print("24")
 elif(name[1]=="y"):
     print("25")
 elif(name[1]=="z"):
     print("26")
 else:
     print("not in the paremitter")
 
 print("Third letter sequence:")
 if(name[2]=="a"):
     print("1")
 elif(name[2]=="b"):
     print("2")
 elif(name[2]=="c"):
     print("3")
 elif(name[2]=="d"):
     print("4")
 elif(name[2]=="e"):
     print("5")
 elif(name[2]=="f"):
     print("6")
 elif(name[2]=="g"):
     print("7")
 elif(name[2]=="h"):
     print("8")
 elif(name[2]=="i"):
     print("9")
 elif(name[2]=="j"):
     print("10")
 elif(name[2]=="k"):
     print("11")
 elif(name[2]=="l"):
     print("12")
 elif(name[2]=="m"):
     print("13")
 elif(name[2]=="n"):
     print("14")
 elif(name[2]=="o"):
     print("15")
 elif(name[2]=="p"):
     print("16")
 elif(name[2]=="q"):
     print("17")
 elif(name[2]=="r"):
     print("18")
 elif(name[2]=="s"):
     print("19")
 elif(name[2]=="t"):
     print("20")
 elif(name[2]=="u"):
     print("21")
 elif(name[2]=="v"):
     print("22")
 elif(name[2]=="w"):
     print("23")
 elif(name[2]=="x"):
     print("24")
 elif(name[2]=="y"):
     print("25")
 elif(name[2]=="z"):
     print("26")
 else:
     print("not in the paremitter")
 
 print("Fourth letter sequence:")
 if(name[3]=="a"):
     print("1")
 elif(name[3]=="b"):
     print("2")
 elif(name[3]=="c"):
     print("3")
 elif(name[3]=="d"):
     print("4")
 elif(name[3]=="e"):
     print("5")
 elif(name[3]=="f"):
     print("6")
 elif(name[3]=="g"):
     print("7")
 elif(name[3]=="h"):
     print("8")
 elif(name[3]=="i"):
     print("9")
 elif(name[3]=="j"):
     print("10")
 elif(name[3]=="k"):
     print("11")
 elif(name[3]=="l"):
     print("12")
 elif(name[3]=="m"):
     print("13")
 elif(name[3]=="n"):
     print("14")
 elif(name[3]=="o"):
     print("15")
 elif(name[3]=="p"):
     print("16")
 elif(name[3]=="q"):
     print("17")
 elif(name[3]=="r"):
     print("18")
 elif(name[3]=="s"):
     print("19")
 elif(name[3]=="t"):
     print("20")
 elif(name[3]=="u"):
     print("21")
 elif(name[3]=="v"):
     print("22")
 elif(name[3]=="w"):
     print("23")
 elif(name[3]=="x"):
     print("24")
 elif(name[3]=="y"):
     print("25")
 elif(name[3]=="z"):
     print("26")
 else:
     print("not in the paremitter")
 
 print("Fifth letter sequence:")
 if(name[4]=="a"):
     print("1")
 elif(name[4]=="b"):
     print("2")
 elif(name[4]=="c"):
     print("3")
 elif(name[4]=="d"):
     print("4")
 elif(name[4]=="e"):
     print("5")
 elif(name[4]=="f"):
     print("6")
 elif(name[4]=="g"):
     print("7")
 elif(name[4]=="h"):
     print("8")
 elif(name[4]=="i"):
     print("9")
 elif(name[4]=="j"):
     print("10")
 elif(name[4]=="k"):
     print("11")
 elif(name[4]=="l"):
     print("12")
 elif(name[4]=="m"):
     print("13")
 elif(name[4]=="n"):
     print("14")
 elif(name[4]=="o"):
     print("15")
 elif(name[4]=="p"):
     print("16")
 elif(name[4]=="q"):
     print("17")
 elif(name[4]=="r"):
     print("18")
 elif(name[4]=="s"):
     print("19")
 elif(name[4]=="t"):
     print("20")
 elif(name[4]=="u"):
     print("21")
 elif(name[4]=="v"):
     print("22")
 elif(name[4]=="w"):
     print("23")
 elif(name[4]=="x"):
     print("24")
 elif(name[4]=="y"):
     print("25")
 elif(name[4]=="z"):
     print("26")
 else:
     print("not in the paremitter")
else:
    print("Enter name between 5 word")